### PR TITLE
Removes config template files with actual config files

### PR DESCRIPTION
**Pull request by geetikabatra**
Ref:https://github.com/openshiftio/openshift.io/issues/2699

### CODE REVIEW

**Comment by tuxdna** [comment]
@GeetikaBatra Why is config.py.template renamed to config.py ?

**Comment by GeetikaBatra** [comment]
@tuxdna, This was in reference to https://github.com/openshiftio/openshift.io/issues/2699. But I guess I will have to supply all the variables in docker environment like this https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file
and have to do away with config.py.

**Comment by tuxdna** [comment]
We can use env variables via docker. However we still need a python module that will read those env variables for rest of our python code. That is what config.py does. We can't do away with config.py. 

Do you think current `config.py.template` and `config.py` setup is broken in any way ?

**Comment by GeetikaBatra** [comment]
@tuxdna, there was a little discussion about config files in flask applications. I think @msrb can shed a little more light on this.

**Comment by GeetikaBatra** [comment]
@tuxdna, I think we need to do away with template files.

**Comment by GeetikaBatra** [comment]
@msrb and @tuxdna, Usually flask applications use config values from app.config. http://flask.pocoo.org/docs/0.12/config/ . I think, instead of doing away with config.py completely. We can implement something like this. WDYT?

**Comment by msrb** [comment]
> Do you think current config.py.template and config.py setup is broken in any way ?

Not really, it's just not what Flask people do (AFAIK) and, to me, it feels confusing. Granted, it's a nitpick but there is more such small things here: code in `src/`, `requirements.txt` which contains runtime and test dependencies.

I think that more confusing things are, more room for errors is there.

Note @GeetikaBatra is not removing the file completely. She just renamed it to `config.py`.

**Comment by tuxdna** [comment]
Note that `config.py.template` represents the configuration parameters and `config.py` represents actual values. We avoid many serious bugs by not having `config.py` in version control --- avoid accidental code commits, which may contain credentials etc.

Does current setup pose any hurdle or issue with development etc. ? My opinion is that we shouldn't fix what isn't broken.

**Comment by tuxdna** [comment]
After discussion in the stand-up today, lets get rid of these template files.

@GeetikaBatra: Approved. Feel free to merge.

**Comment by GeetikaBatra** [comment]
Thanks @tuxdna.  👍

**Pull request merged**
