### PR TITLE
Wait for gremlin service to be up before starting web workers

### PR DESCRIPTION
**Pull request by tuxdna**
Fixes: https://github.com/fabric8-analytics/fabric8-analytics-common/issues/296

### CODE REVIEW

**Comment by tuxdna** [comment]
@fridex That doesn't make sense. It is infact `gunicorn` that restarts the web-workers. The failure logs are replaced with a self-explanatory message that says 

```
Waiting for Gremlin HTTP Server...
```

In case data-model importer is restarted, it will wait until the target gremlin server is up. Till that time it will print the above message every 2 seconds. Besides, this is very useful to trim down the number of un-necessary stack-traces shown in logs right now.

**Comment by fridex** [comment]
> @fridex That doesn't make sense. It is infact gunicorn that restarts the web-workers. The failure logs are replaced with a self-explanatory message that says

In that case data-importer handles this in a wrong way. Service shouldn't start unless there are all resources prepared - it should keep restarting and signalling errors (that's what I was expecting).

So to fix this, data-importer should set up graph database before the web server is started. This will be soon handled as we move data-importer to worker. Anyway, we will get rid of data-importer (the patch is WIP) so this change is not needed.

**Comment by tuxdna** [comment]
This PR is only to reduce the clutter generated by unnecessary error logs. Initialization, synchronization etc. are out of scope of this PR.

Even if this component is moved to worker, the Gremlin server still will be separate component from  data-model importer. Gremlin server takes its own time to initialize as it is designed to run as a separate service.

Data Model doesn't handle initialization of Gremlin server in any way, and it really shouldn't because these two are separate (micro-)services. The only thing we need is a way for Data Model importer to know that Gremlin is now up, so it can proceed with running web-workers.

This change is very useful at-least for me to not deal with redundant error messages.

**Comment by tuxdna** [comment]
@fridex Thanks for merging this PR.

**Comment by jpopelka** [comment]
Thanks @tuxdna, that messages were annoying.

**Pull request merged**
