### PR TITLE
Fix 'E722 do not use bare except' + some code refactoring

### PR DESCRIPTION
**Pull request by jpopelka**
Fixes https://github.com/openshiftio/openshift.io/issues/1004

### CODE REVIEW

**Comment by tisnik** [comment]
@jpopelka looks ok (giving we don't know which exception types are expected ;)

**Comment by tisnik** [comment]
[test this]

**Comment by pkajaba** [comment]
[test]

**Comment by tisnik** [comment]
looks ok @jpopelka , but could you please rebase & resolve conflicts?

**Comment by jpopelka** [comment]
rebased

**Pull request merged**
