### PR TITLE
Exclude unfinished analyses from graph sync queries

### PR DESCRIPTION
**Pull request by msrb**
Fixes https://github.com/openshiftio/openshift.io/issues/2313.

### CODE REVIEW

**Comment by tuxdna** [comment]
@msrb Please fix the pylint errors.

**Comment by msrb** [comment]
@tuxdna I haven't introduced any :) That's newer version of pycodestyle complaining about existing code.

**Comment by tuxdna** [comment]
[test]

**Comment by tuxdna** [comment]
[test]

**Pull request merged**
