### PR TITLE
Remove unused code

### PR DESCRIPTION
**Pull request by tuxdna**
Fixes: https://github.com/fabric8-analytics/fabric8-analytics-data-model/issues/128

### CODE REVIEW

**Comment by tuxdna** [comment]
[test]

**Comment by jpopelka** [comment]
rebase and rerun tests please

**Comment by tuxdna** [comment]
@jpopelka The tests pass now. PTAL.

**Comment by sara-02** [comment]
@tuxdna @jpopelka LGTM merging this.

**Pull request merged**
