### PR TITLE
[openshift] Increase timeout in health checks

### PR DESCRIPTION
**Pull request by msrb**

### CODE REVIEW

**Comment by msrb** [comment]
cc @miteshvp PTAL. There are some timeouts in prod. 5 second timeout is too lean.

**Comment by miteshvp** [comment]
LGTM. @msrb - Are you seeing this too often, or its like rare?

**Comment by msrb** [comment]
@miteshvp data-importer containers were restarted 50 times in last two days, so I'd say it's too often.

**Comment by miteshvp** [comment]
👍

**Pull request merged**
